"""Check whether the Brain Panel pipeline produces consistent z-scores
across runs.

If the rule-IN PPV drop on the new 242 cohort is a methodology issue
(option 1) rather than a real overfit (option 3), the z-score
distributions should differ between PDFs generated by different
pipeline versions.

Compare three groups of EDFs (same EC_191 reference DB, same expected
panel, same Dr. Ims label distribution -- only the pipeline run differs):

  A) Original n=100 cohort: PDFs that ALREADY EXISTED before this session
     (77 of them, generated by an earlier pipeline run -- could be the
     production code, the development code, or hand-curated outputs).
  B) Original n=100 cohort: PDFs I FRESHLY GENERATED in this session
     (23 of them, run via process_missing_edfs.py).
  C) New 242-EDF cohort: PDFs I FRESHLY GENERATED in this session
     (242 of them, run via process_new_cohort.py).

If the z-score distribution for, say, "Diffuse Hibeta" looks the same
across A, B, C -> the rule-IN flags really don't generalize (option 3).

If A differs from B+C -> pipeline version drift (option 1).

We also flag any metric whose mean shifts > 0.5 z across groups as a
candidate culprit for the rule-IN PPV drop.
"""
import csv
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from panel_parser import NAME_STRINGS, parse_panel_pdf  # noqa: E402

OUT = os.path.join(HERE, "out")
LOG_MISSING = os.path.join(OUT, "process_missing_edfs.log")
LOG_NEW = os.path.join(OUT, "process_new_cohort.log")
ORIG_MATCH = os.path.join(OUT, "original_cohort_match.csv")
NEW_LABELS = os.path.join(OUT, "new_cohort_labels.csv")


def find_pdf(edf_path):
    if not edf_path: return None
    bn = os.path.basename(edf_path).replace(".edf", "")
    d = os.path.dirname(edf_path)
    for sub in ("", "output", "output version 1"):
        cand = os.path.join(d, sub, bn + ".icale.rep.pdf")
        if os.path.exists(cand):
            return cand
    return None


def fresh_processed_edfs(log_path):
    """Return set of EDF basenames that the log says were OK-processed."""
    out = set()
    if not os.path.exists(log_path):
        return out
    with open(log_path, encoding="utf-8") as f:
        for line in f:
            if " OK " in line and ".edf" in line.lower():
                # last whitespace-token is the EDF basename (truncated)
                bn = line.rstrip().split()
                if bn:
                    out.add(bn[-1].lower())
    return out


def parse_z(pdf_path):
    try:
        r = parse_panel_pdf(pdf_path)
        if r.get("valid"):
            return r["zscores"]
    except Exception:
        pass
    return None


def main():
    fresh_missing = fresh_processed_edfs(LOG_MISSING)
    fresh_new     = fresh_processed_edfs(LOG_NEW)
    print(f"Found {len(fresh_missing)} fresh-from-missing-batch EDF basenames")
    print(f"Found {len(fresh_new)} fresh-from-new-cohort EDF basenames")

    # Group A: original n=100 with PDFs that pre-existed this session
    # Group B: original n=100 with PDFs I freshly generated
    # Group C: new 242 cohort (all freshly generated)
    groups = {"A_orig_existing": [], "B_orig_fresh": [], "C_new_fresh": []}

    orig_rows = list(csv.DictReader(open(ORIG_MATCH, encoding="utf-8")))
    for r in orig_rows:
        edf = r["edf_path"]
        pdf = find_pdf(edf)
        if pdf is None:
            continue
        bn = os.path.basename(edf).lower()
        # If we processed it in this session via process_missing_edfs.py,
        # then it's in fresh_missing.
        if any(bn.startswith(x[:50]) or x.startswith(bn[:50]) for x in fresh_missing):
            groups["B_orig_fresh"].append((edf, pdf))
        else:
            groups["A_orig_existing"].append((edf, pdf))

    new_rows = list(csv.DictReader(open(NEW_LABELS, encoding="utf-8")))
    for r in new_rows:
        edf = r["edf_path"]
        pdf = find_pdf(edf)
        if pdf is None:
            continue
        groups["C_new_fresh"].append((edf, pdf))

    for k, v in groups.items():
        print(f"  {k}: {len(v)} EDFs")
    print()

    # Parse z-scores for each group (cap at first 80 per group to keep
    # this snappy, but use ALL of original cohort which is < 100 anyway)
    z_by_group = {}
    for gname, lst in groups.items():
        zs = []
        sample = lst[:200]  # cap large group
        for edf, pdf in sample:
            z = parse_z(pdf)
            if z is not None:
                zs.append(z)
        z_by_group[gname] = np.array(zs)
        print(f"  parsed {len(zs)} z-score vectors from group {gname}")
    print()

    # Compare distributions
    print("=" * 110)
    print(f"{'Metric':<22} "
          f"{'A_orig_existing':<22} {'B_orig_fresh':<20} {'C_new_fresh':<22}"
          f" {'D(C-A)':>7} {'flag?':>6}")
    print("=" * 110)

    important = []
    for i, name in enumerate(NAME_STRINGS):
        stats = {}
        for g in ["A_orig_existing", "B_orig_fresh", "C_new_fresh"]:
            Z = z_by_group[g]
            if Z.shape[0] == 0:
                stats[g] = (float("nan"), float("nan"))
                continue
            col = Z[:, i]
            col = col[~np.isnan(col)]
            stats[g] = (col.mean(), col.std())
        m_a, s_a = stats["A_orig_existing"]
        m_b, s_b = stats["B_orig_fresh"]
        m_c, s_c = stats["C_new_fresh"]
        delta_ca = m_c - m_a
        flag = ""
        if not np.isnan(delta_ca) and abs(delta_ca) > 0.5:
            flag = "**"
            important.append((name, m_a, m_b, m_c, s_a, s_b, s_c))
        print(f"{name:<22} "
              f"{m_a:>+6.2f}±{s_a:<5.2f} (n={(z_by_group['A_orig_existing'].shape[0]):>3}) "
              f"{m_b:>+6.2f}±{s_b:<5.2f} (n={z_by_group['B_orig_fresh'].shape[0]:>2}) "
              f"{m_c:>+6.2f}±{s_c:<5.2f} (n={z_by_group['C_new_fresh'].shape[0]:>3}) "
              f"{delta_ca:>+7.2f}  {flag:>5}")

    print()
    print(f"Metrics with |D mean (C-A)| > 0.5: {len(important)}")
    if important:
        print()
        print("** Metrics flagged as drifting between cohorts:")
        for name, m_a, m_b, m_c, s_a, s_b, s_c in important:
            print(f"   {name:<22}  A={m_a:+.2f}  B={m_b:+.2f}  C={m_c:+.2f}")

    # If group B and C agree but A differs from both, that's pipeline drift.
    # If A and B agree (both = original-cohort) and C differs, that's a
    # cohort-composition issue, not pipeline.
    print()
    print("Diagnostic:")
    print("  - If B ~ C but A differs => pipeline version drift")
    print("  - If A ~ B (original) but C differs => cohort composition")
    print("  - If A ~ B ~ C => the rule-IN PPV drop is a real overfit")
    print()

    # Quantify: average abs(mean) difference
    diffs = {"|A-B|": [], "|B-C|": [], "|A-C|": []}
    for i in range(48):
        ma = z_by_group["A_orig_existing"][:, i].mean() \
            if z_by_group["A_orig_existing"].shape[0] else np.nan
        mb = z_by_group["B_orig_fresh"][:, i].mean() \
            if z_by_group["B_orig_fresh"].shape[0] else np.nan
        mc = z_by_group["C_new_fresh"][:, i].mean() \
            if z_by_group["C_new_fresh"].shape[0] else np.nan
        if not np.isnan(ma) and not np.isnan(mb):
            diffs["|A-B|"].append(abs(ma - mb))
        if not np.isnan(mb) and not np.isnan(mc):
            diffs["|B-C|"].append(abs(mb - mc))
        if not np.isnan(ma) and not np.isnan(mc):
            diffs["|A-C|"].append(abs(ma - mc))

    print("Mean of |mean differences| across all 48 metrics:")
    for k, v in diffs.items():
        if v:
            print(f"  {k}: {np.mean(v):.3f} (median {np.median(v):.3f}, max {max(v):.2f})")


if __name__ == "__main__":
    main()
